# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'datos.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_datos(object):
    def setupUi(self, datos):
        datos.setObjectName("datos")
        datos.resize(1005, 598)
        self.centralwidget = QtWidgets.QWidget(datos)
        self.centralwidget.setObjectName("centralwidget")
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(30, 30, 831, 501))
        self.table.setObjectName("table")
        self.table.setColumnCount(2)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        datos.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(datos)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1005, 18))
        self.menubar.setObjectName("menubar")
        datos.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(datos)
        self.statusbar.setObjectName("statusbar")
        datos.setStatusBar(self.statusbar)

        self.retranslateUi(datos)
        QtCore.QMetaObject.connectSlotsByName(datos)

    def retranslateUi(self, datos):
        _translate = QtCore.QCoreApplication.translate
        datos.setWindowTitle(_translate("datos", "datos"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("datos", "Materia"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("datos", "Status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    datos = QtWidgets.QMainWindow()
    ui = Ui_datos()
    ui.setupUi(datos)
    datos.show()
    sys.exit(app.exec_())
